name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/huacnlee/rails-docker-build:$(date +%s)
    - name: Push the Docker image
      run: |
        docker login docker.pkg.github.com -u huacnlee -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/huacnlee/rails-docker-build:$(date +%s)

